### ISSUE TITLE
Support parallel projects check

### ISSUE THREAD

**Issue by imanushin** [Litee/SolutionCop#17]
Some solutions have 50-100 projects, so it is better to check them as parallel

**Comment by Litee** [comment]
Igor, have you estimated the potential gain?

**Comment by imanushin** [comment]
@Litee , I checked and decided to postpone this enhancement until more rules will be used. Whole checking time (for ~70 projects) is about 3-5 seconds.

**Comment by Litee** [comment]
Will close for now
