### ISSUE TITLE
Check, that all references from the packages folder exists in packages.config file

### ISSUE THREAD

**Issue by imanushin** [Litee/SolutionCop#18]
Steps to reproduce:
1. Create two projects.
2. Install package Jetbrains.Annotations 9.0 to the first
3. Reference file Jetbrains.Annotations.dll from the second project direct from the packages folder.
4. Update nuget reference Jetbrains.Annotations in all projects, which have it (e.g. only first project will update the package)
5. Second project will reference to nonexistent file

So, it is better to have rule, which will prevent referencing from packages folder without package installation.

**Comment by Litee** [comment]
There is such check, but it was ignored when there is no packages.config file. Now fixed.
