### ISSUE TITLE
Add artifacts to releases

### ISSUE THREAD

**Issue by AlenPelin** [Litee/SolutionCop#20]
As I can see you have releases on GitHub, but none of them have artifacts (binaries) attached. It would be much more convenient if they had artifacts in each release - I believe team city can do that for you. At the moment it is not clear at all where to download the artifacts.

**Comment by Litee** [comment]
All binaries are hosted at NuGet - https://www.nuget.org/packages/SolutionCop/
I doubt anyone needs pure binaries these days.

**Comment by AlenPelin** [comment]
In my opinion NuGet is designed for assemblies that you add references to in Visual Studio solution whilest Chocolatey is for executable apps that you install onto machine once and run multiple times.

**Comment by Litee** [comment]
Choco makes sense. Do you want to build a package that will reference binaries hosted at GitHub?

**Comment by AlenPelin** [comment]
No, at least not now. I am just evaluating this project (after reading habr article). I have own similar project that resolves this issue from straight another side: https://github.com/alienlab/Alienlab.VSProj/releases
