### ISSUE TITLE
'Warning level 0 is lower than required' false error

### ISSUE THREAD

**Issue by sm-g** [Litee/SolutionCop#21]
csproj: http://pastebin.com/tipA27Lq

**Comment by Litee** [comment]
What level was specified in rules?

**Comment by sm-g** [comment]
4

**Comment by Litee** [comment]
Then there is no mistake - I can see in project settings that level 4 is provided for some configurations only - e.g. warning level 1 will be used for "Debug|x64".

Does it make sense?

**Comment by sm-g** [comment]
Oh, you are right of course. VS shows them as setted and I overlooked real xml. Maybe add some info to output about PropertyGroup condition?
