### ISSUE TITLE
FilesIncludedIntoProject wrong file path in output

### ISSUE THREAD

**Issue by sm-g** [Litee/SolutionCop#22]
Files located in Project\DAL\Migrations\...
shows as: File is not referenced in project: DAL\ect\DAL\Migrations\..

in YandexBanks\...
as YandexBanks\exBanks\...

**Comment by Litee** [comment]
Could you provide more details about csproj and file locations + how file reference looks like in csproj?

**Comment by sm-g** [comment]
Found myself, GetDirectoryName returns ".\..\..\DAL", fix: http://ge.tt/9G0gjES2/v/0

**Comment by Litee** [comment]
Link doesn't work - getting "File not available"

**Comment by sm-g** [comment]
https://gist.github.com/sm-g/cf0e1d6092398089a57c
