### ISSUE TITLE
TreatStyleCopWarningsAsErrors

### ISSUE THREAD

**Issue by skurdiukov** [Litee/SolutionCop#45]
TreatStyleCopWarningsAsErrors actually pass when StyleCopTreatErrorsAsWarnings set to **true**, allowing ignore stylecop violations. Is this intended behavior?

**Comment by Litee** [comment]
Oops, you are totally right. Will fix. Sorry for taking so long to get back.

**Comment by Litee** [comment]
Fixed in v0.9.0
